In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [4]:
np.array([10,20,30])

array([10, 20, 30])

In [5]:
np.array([10,10.9,"poornima"])

array(['10', '10.9', 'poornima'], dtype='<U32')

In [8]:
a=np.random.rand(4,4)
a

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [9]:
a.dtype

dtype('float64')

In [10]:
np.dtype

numpy.dtype

In [13]:
a[2]

array([0.13381769, 0.65398644, 0.24027367, 0.41505553])

In [14]:
a[-1]

array([0.36228421, 0.06539547, 0.16763515, 0.97992279])

In [15]:
a

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [16]:
a[::-1]

array([[0.36228421, 0.06539547, 0.16763515, 0.97992279],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.91737046, 0.4106715 , 0.56796424, 0.45274162]])

In [17]:
a[::,::-1]

array([[0.45274162, 0.56796424, 0.4106715 , 0.91737046],
       [0.78675974, 0.98485203, 0.1628825 , 0.03743174],
       [0.41505553, 0.24027367, 0.65398644, 0.13381769],
       [0.97992279, 0.16763515, 0.06539547, 0.36228421]])

#fetch index 0 & 2 rows


In [18]:
a[::2]

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553]])

In [20]:
a

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

#fetch 2nd & 4th row

In [19]:
a[1::2]

array([[0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

#assignment
#access last 2 rows
#access middle 2 rows
#access 1st and last row
#access 2nd and last row
#access last 3 rows

In [21]:
a

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [23]:
a[2:]

array([[0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [24]:
a[1:3]

array([[0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553]])

In [25]:
a

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [28]:
a[::3]

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [29]:
a[1::2]

array([[0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [30]:
a

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [31]:
a[1:]

array([[0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [34]:
a[:,0]

array([0.91737046, 0.03743174, 0.13381769, 0.36228421])

#assignment
#access corner elements
#access diagonal elements
#access middle 2 columns and all rows
#access last 2 rows and its first 2 values from each row
#reverse rows & columns

In [35]:
a

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [37]:
a[::3,::3]

array([[0.91737046, 0.45274162],
       [0.36228421, 0.97992279]])

In [38]:
a.diagonal()

array([0.91737046, 0.1628825 , 0.24027367, 0.97992279])

In [39]:
a[:,1:3]

array([[0.4106715 , 0.56796424],
       [0.1628825 , 0.98485203],
       [0.65398644, 0.24027367],
       [0.06539547, 0.16763515]])

In [41]:
a[2:,:2]

array([[0.13381769, 0.65398644],
       [0.36228421, 0.06539547]])

In [42]:
a[::-1,::-1]

array([[0.97992279, 0.16763515, 0.06539547, 0.36228421],
       [0.41505553, 0.24027367, 0.65398644, 0.13381769],
       [0.78675974, 0.98485203, 0.1628825 , 0.03743174],
       [0.45274162, 0.56796424, 0.4106715 , 0.91737046]])

In [43]:
a.shape

(4, 4)

In [44]:
a.ndim

2

Convert any dim to 1 dim(temporarily)

In [45]:
a.ravel()

array([0.91737046, 0.4106715 , 0.56796424, 0.45274162, 0.03743174,
       0.1628825 , 0.98485203, 0.78675974, 0.13381769, 0.65398644,
       0.24027367, 0.41505553, 0.36228421, 0.06539547, 0.16763515,
       0.97992279])

In [47]:
a.resize(2,2,4)
a

array([[[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
        [0.03743174, 0.1628825 , 0.98485203, 0.78675974]],

       [[0.13381769, 0.65398644, 0.24027367, 0.41505553],
        [0.36228421, 0.06539547, 0.16763515, 0.97992279]]])

In [48]:
a.reshape(4,4)

array([[0.91737046, 0.4106715 , 0.56796424, 0.45274162],
       [0.03743174, 0.1628825 , 0.98485203, 0.78675974],
       [0.13381769, 0.65398644, 0.24027367, 0.41505553],
       [0.36228421, 0.06539547, 0.16763515, 0.97992279]])

In [50]:
a.T

array([[[0.91737046, 0.13381769],
        [0.03743174, 0.36228421]],

       [[0.4106715 , 0.65398644],
        [0.1628825 , 0.06539547]],

       [[0.56796424, 0.24027367],
        [0.98485203, 0.16763515]],

       [[0.45274162, 0.41505553],
        [0.78675974, 0.97992279]]])

In [51]:
np.transpose(a)

array([[[0.91737046, 0.13381769],
        [0.03743174, 0.36228421]],

       [[0.4106715 , 0.65398644],
        [0.1628825 , 0.06539547]],

       [[0.56796424, 0.24027367],
        [0.98485203, 0.16763515]],

       [[0.45274162, 0.41505553],
        [0.78675974, 0.97992279]]])