In [1]:
import numpy as np

In [3]:
a=np.random.rand(4,4)
a

array([[0.02880628, 0.96989636, 0.92149574, 0.65614976],
       [0.3478205 , 0.70679814, 0.50707976, 0.99983467],
       [0.09100749, 0.53702105, 0.77016335, 0.46543606],
       [0.82553335, 0.52674372, 0.73736596, 0.3379705 ]])

In [4]:
a[:]

array([[0.02880628, 0.96989636, 0.92149574, 0.65614976],
       [0.3478205 , 0.70679814, 0.50707976, 0.99983467],
       [0.09100749, 0.53702105, 0.77016335, 0.46543606],
       [0.82553335, 0.52674372, 0.73736596, 0.3379705 ]])

In [5]:
a[0]

array([0.02880628, 0.96989636, 0.92149574, 0.65614976])

In [6]:
a[::-1]

array([[0.82553335, 0.52674372, 0.73736596, 0.3379705 ],
       [0.09100749, 0.53702105, 0.77016335, 0.46543606],
       [0.3478205 , 0.70679814, 0.50707976, 0.99983467],
       [0.02880628, 0.96989636, 0.92149574, 0.65614976]])

In [8]:
a[:,: : -1]

array([[0.65614976, 0.92149574, 0.96989636, 0.02880628],
       [0.99983467, 0.50707976, 0.70679814, 0.3478205 ],
       [0.46543606, 0.77016335, 0.53702105, 0.09100749],
       [0.3379705 , 0.73736596, 0.52674372, 0.82553335]])

#fetch index 0 & 2 rows

In [10]:
a

array([[0.02880628, 0.96989636, 0.92149574, 0.65614976],
       [0.3478205 , 0.70679814, 0.50707976, 0.99983467],
       [0.09100749, 0.53702105, 0.77016335, 0.46543606],
       [0.82553335, 0.52674372, 0.73736596, 0.3379705 ]])

In [9]:
a[::2]

array([[0.02880628, 0.96989636, 0.92149574, 0.65614976],
       [0.09100749, 0.53702105, 0.77016335, 0.46543606]])

#fetch 2nd & 4th row

In [12]:
a[1::2]

array([[0.3478205 , 0.70679814, 0.50707976, 0.99983467],
       [0.82553335, 0.52674372, 0.73736596, 0.3379705 ]])

#assignment
#access last 2 rows
#access middle 2 rows
#access 1st and last row
#access 2nd and last row
#access last 3 rows

In [13]:
a[2::]

array([[0.09100749, 0.53702105, 0.77016335, 0.46543606],
       [0.82553335, 0.52674372, 0.73736596, 0.3379705 ]])

In [15]:
a[1:3:]

array([[0.3478205 , 0.70679814, 0.50707976, 0.99983467],
       [0.09100749, 0.53702105, 0.77016335, 0.46543606]])

In [17]:
np.array([1,2,3])

array([1, 2, 3])

In [18]:
import pandas as pd

In [21]:
pd.Series(dtype=object)

Series([], dtype: object)

In [22]:
k=[10,'poornima',10.9]
pd.Series(k)

0          10
1    poornima
2        10.9
dtype: object

In [19]:
pd.__version__

'1.5.3'

In [20]:
pd.Series?

In [23]:
pd.Series([10,20,30.8])

0    10.0
1    20.0
2    30.8
dtype: float64

In [24]:
pd.Series([10,30.2,10j])

0    10.0+0.0j
1    30.2+0.0j
2    0.0+10.0j
dtype: complex128

In [27]:
a=pd.Series([10,20,30])
a

0    10
1    20
2    30
dtype: int64

In [28]:
a.size

3

In [29]:
len(a)

3

In [31]:
a.count()

3

Nan has been ignored(hence the count =2)

In [36]:
d=pd.Series([10,20,np.nan])
d

0    10.0
1    20.0
2     NaN
dtype: float64

In [37]:
d.count()

2

shape returns the row,col but series is 1 dim hence return only number of rows

In [38]:
d.shape

(3,)

Returns number of dimensions

In [39]:
d.ndim

1

Check the memory usage

In [41]:
d.memory_usage()

152

Fetch the values

In [42]:
d.values

array([10., 20., nan])

Fetch the index

In [43]:
d.index

RangeIndex(start=0, stop=3, step=1)

Mathematical operations

In [44]:
e=pd.Series([120,1,9000,22,18])
e

0     120
1       1
2    9000
3      22
4      18
dtype: int64

Find the maximum values

In [46]:
e.max()

9000

Find Min value

In [47]:
e.min()

1

Cental Measures of Tendencies (Mean,Median,Mode)

Find the average

In [48]:
e.mean()

1832.2

Sort the values then returns the middle element
120
1
9000
22
18

first sort the values
1,18,22,120,9000

then return the middle value
22

if the total numbers are even 
sort->add two middle number/2

In [49]:
e.median()

22.0

Mode returns maximum repeated numbers(Ex: here 10 is most repeated number in the given series)

In [55]:
f=pd.Series([10,20,10,10,30,444])
f
f.mode()

0    10
dtype: int64

Assignment

1)Create series of [40,2,4,670,,7,90,1,20]
2)Check all the properties

Find occarance of each values

In [57]:
e.value_counts()

120     1
1       1
9000    1
22      1
18      1
dtype: int64

Find occarance of each values using numpy(the result will be in boolean)

In [62]:
e == 22

0    False
1    False
2    False
3     True
4    False
dtype: bool

convert boolean result into actual value 

In [63]:
e[e == 22]

3    22
dtype: int64

check the count of the occurance

In [64]:
e[e == 22].size

1